language: cpp

install:
  - export INITIAL_DIR=$PWD
  - echo ========== INSTALLING CMAKE 3.6 ==========
  - python .download_cmake_travis.py
  - source cmakeEnv.sh
  - echo ========== BUILDING AND INSTALLING GOOGLE TEST ==========
  - git clone https://github.com/google/googletest
  - cd googletest
  - git checkout release-1.8.0
  - mkdir myBuild
  - cd myBuild
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/myInstall ..
  - export PATH=$PWD/myInstall:$PATH
  - export CMAKE_PREFIX_PATH=$PWD/myInstall:$CMAKE_PREFIX_PATH
  - make
  - make install
  - cd $INITIAL_DIR

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - ARCHIVE_NAME_CMAKE=cmake-3.6.2-Linux-x86_64
    - os: linux
      compiler: clang
      env:
        - COMPILER=clang
        - ARCHIVE_NAME_CMAKE=cmake-3.6.2-Linux-x86_64
    # - os: osx
    #   compiler: clang
    #   env: COMPILER=clang

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script: make all test
