language: cpp

sudo: required
dist: trusty

before_install:
  - sudo deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu xenial main 
  - sudo deb-src http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu xenial main 
  - sudo apt-get update -q
  - sudo apt-get install cmake -y
  - git clone https://github.com/google/googletest
  - pwd
  - cd googletest
  - mkdir myBuild
  - cd myBuild
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - pwd

compiler: clang

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
