language: cpp

sudo: required
dist: trusty

before_install:
  - git clone https://github.com/google/googletest
  - pwd
  - cd googletest
  - mkdir myBuild
  - cd myBuild
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - pwd

compiler: clang

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
