language: cpp

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.5 -y
  - sudo apt-get update -q
  - sudo apt-get install cmake -y

compiler: clang

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
