language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
      apt:
        sources:
          -llvm-toolchain-precise-3.8
          -george-edison55/cmake-3.5
        packages:
          -clang-3.8
          -cmake
      env: COMPILER=clang++-3.8

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
