language: cpp

install:
  - export INITIAL_DIR=$PWD
  - wget --no-check-certificate https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar -xvf /tmp/cmake.tar.gz
  - export PATH=$PWD/cmake-3.6.2-Linux-x86_64/bin/:$PATH
  - git clone https://github.com/google/googletest
  - cd googletest
  - mkdir myBuild
  - cd myBuild
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/myInstall ..
  - export PATH=$PWD/myInstall:$PATH
  - export CMAKE_PREFIX_PATH=$PWD/myInstall:$CMAKE_PREFIX_PATH
  - make
  - make install
  - cd $INITIAL_DIR

compiler:
  - clang

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make all test
