language: cpp

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -q
  - sudo apt-get install cmake -y
  - git clone https://github.com/google/googletest
  - cd googletest
  - mkdir myBuild
  - cd myBuild
  - cmake ..
  - make
  - sudo make install
  - cd ~

compiler: clang

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
