language: cpp

compiler: clang

branches:
  only:
  - master

before_script:
  - wget https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar -xvf /tmp/cmake.tar.gz
  - export PATH=$PWD/cmake-3.6.2-Linux-x86_64/bin/:$PATH
  - mkdir build
  - cd build
  - cmake ..

script: make
