language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8', 'kalakris-cmake']
        packages: ['clang-3.8', 'cmake']
      env: COMPILER=clang++-3.8

branches:
  only:
  - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
